In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('../lecture11/imdb-top-1000.csv')
mobiles = pd.read_csv('../lecture10/mobiles.csv')

In [3]:
movies.sample(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
165,Casino,1995,178,Crime,8.2,Martin Scorsese,Robert De Niro,466276,42438300.0,73.0
296,Ivanovo detstvo,1962,95,Drama,8.1,Andrei Tarkovsky,Eduard Abalov,31728,388466313.0,NaN

In [4]:
# agg method
genre = movies.groupby('Genre')

In [ ]:
genre.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [6]:
genre.agg(
    {
        'Runtime': 'mean',
        'IMDB_Rating': 'sum',
        'No_of_Votes': 'sum',
        'Gross': 'min',
        'Series_Title': 'first'
    }
)

,Runtime,IMDB_Rating,No_of_Votes,Gross,Series_Title
Genre,,,,,
Action,129.046512,1367.3,72282412,3296.0,The Dark Knight
Adventure,134.111111,571.5,22576163,61001.0,Interstellar
Animation,99.585366,650.3,21978630,128985.0,Sen to Chihiro no kamikakushi
Biography,136.022727,698.6,24006844,21877.0,Schindler's List
Comedy,112.129032,1224.7,27620327,1305.0,Gisaengchung
Crime,126.392523,857.8,33533615,6013.0,The Godfather
Drama,124.737024,2299.7,61367304,3600.0,The Shawshank Redemption
Family,107.500000,15.6,551221,4000000.0,E.T. the Extra-Terrestrial
Fantasy,85.000000,16.0,146222,337574718.0,Das Cabinet des Dr. Caligari
Film-Noir,104.000000,23.9,367215,449191.0,The Third Man
Horror,102.090909,87.0,3742556,89029.0,Psycho
Mystery,119.083333,95.7,4203004,1035953.0,Memento
Thriller,108.000000,7.8,27733,17550741.0,Wait Until Dark
Western,148.250000,33.4,1289665,5321508.0,"Il buono, il brutto, il cattivo"

In [7]:
# passing list
genre.agg(['min', 'max'])

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                               Released_Year       Runtime  \
                                           max           min   max     min
Genre
Action                                 Yôjinbô          1924  2019      45
Adventure                           Zombieland          1925    PG      88
Animation          Ôkami kodomo no Ame to Yuki          1940  2020      71
Biography                              Zerkalo          1928  2020      93
Comedy                Zindagi Na Milegi Dobara          1921  2020      68
Crime                        À bout de souffle          1931  2019      80
Drama                                Zwartboek          1925  2020      64
Family     Willy Wonka & the Chocolate Factory          1971  1982     100
Fantasy                              Nosferatu          1920  1922      76
Film-Noir                        The Third Man          1941  1949     100
Horror                               The Thing          1933  2017      71
Mystery                                Vertigo          1938  2012      96
Thriller                       Wait Until Dark          1967  1967     108
Western                 The Outlaw Josey Wales          1965  1976     132

               IMDB_Rating                    Director                    \
           max         min  max                    min               max
Genre
Action     321         7.6  9.0       Abhishek Chaubey       Zack Snyder
Adventure  228         7.6  8.6         Akira Kurosawa  Ömer Faruk Sorak
Animation  137         7.6  8.6            Adam Elliot   Yoshifumi Kondô
Biography  209         7.6  8.9             Adam McKay      Tom McCarthy
Comedy     188         7.6  8.6  Alejandro G. Iñárritu       Zoya Akhtar
Crime      229         7.6  9.2         Akira Kurosawa      Yavuz Turgul
Drama      242         7.6  9.3             Aamir Khan       Çagan Irmak
Family     115         7.8  7.8             Mel Stuart  Steven Spielberg
Fantasy     94         7.9  8.1            F.W. Murnau      Robert Wiene
Film-Noir  108         7.8  8.1       Alfred Hitchcock       John Huston
Horror     122         7.6  8.5     Alejandro Amenábar  William Friedkin
Mystery    138         7.6  8.4            Alex Proyas     Terry Gilliam
Thriller   108         7.8  7.8          Terence Young     Terence Young
Western    165         7.8  8.8         Clint Eastwood      Sergio Leone

                              Star1                   No_of_Votes           \
                                min               max         min      max
Genre
Action                   Aamir Khan      Yun-Fat Chow       25312  2303232
Adventure                Aamir Khan      Yves Montand       29999  1512360
Animation             Adrian Molina      Yôji Matsuda       25229   999790
Biography              Adrien Brody     Éric Toledano       27254  1213505
Comedy                   Aamir Khan  Ömer Faruk Sorak       26337   939631
Crime                    Ajay Devgn    Vincent Cassel       27712  1826188
Drama                    Abhay Deol    Çetin Tekindor       25088  2343110
Family                  Gene Wilder      Henry Thomas      178731   372490
Fantasy                 Max Schreck     Werner Krauss       57428    88794
Film-Noir           Humphrey Bogart     Teresa Wright       59556   158731
Horror              Anthony Perkins  Sigourney Weaver       27007   787806
Mystery    Bernard-Pierre Donnadieu       Vidya Balan       33982  1129894
Thriller             Audrey Hepburn    Audrey Hepburn       27733    27733
Western              Clint Eastwood       Henry Fonda       65659   688390

                 Gross              Metascore
                   min          max       min    max
Genre
Action          3296.0  936662225.0      33.0   98.0
Adventure      61001.0  874211619.0      41.0  100.0
Animation     128985.0  873839108.0      61.0   96.0
Biography      21877.0  753585104.0      48.0   97.0
Comedy          1305.0  886752933.0      45.0   99.0
Crime           6013.0  790482117.0      47.0  100.0
Drama           3600.0  924558264.0      28.0  100.0
Family       4000000.0  435110554.0      67.0   91.0
Fantasy    337574718.0  445151978.0       NaN    NaN
Film-Noir     449191.0  123353292.0      94.0   97.0
Horror         89029.0  298791505.0      46.0   97.0
Mystery      1035953.0  474203697.0      52.0  100.0
Thriller    17550741.0   17550741.0      81.0   81.0
Western      5321508.0   31800000.0      69.0   90.0

In [17]:
movies.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='object')

In [9]:
# Adding both the syntax
genre.agg(
    {
        'Released_Year': ['min', 'max'],
        'Runtime': 'mean',
        'IMDB_Rating': ['min', 'max'],
        'No_of_Votes': ['min', 'max']
    }
)

          Released_Year           Runtime IMDB_Rating      No_of_Votes  \
                    min   max        mean         min  max         min
Genre
Action             1924  2019  129.046512         7.6  9.0       25312
Adventure          1925    PG  134.111111         7.6  8.6       29999
Animation          1940  2020   99.585366         7.6  8.6       25229
Biography          1928  2020  136.022727         7.6  8.9       27254
Comedy             1921  2020  112.129032         7.6  8.6       26337
Crime              1931  2019  126.392523         7.6  9.2       27712
Drama              1925  2020  124.737024         7.6  9.3       25088
Family             1971  1982  107.500000         7.8  7.8      178731
Fantasy            1920  1922   85.000000         7.9  8.1       57428
Film-Noir          1941  1949  104.000000         7.8  8.1       59556
Horror             1933  2017  102.090909         7.6  8.5       27007
Mystery            1938  2012  119.083333         7.6  8.4       33982
Thriller           1967  1967  108.000000         7.8  7.8       27733
Western            1965  1976  148.250000         7.8  8.8       65659


               max
Genre
Action     2303232
Adventure  1512360
Animation   999790
Biography  1213505
Comedy      939631
Crime      1826188
Drama      2343110
Family      372490
Fantasy      88794
Film-Noir   158731
Horror      787806
Mystery    1129894
Thriller     27733
Western     688390

In [10]:
#  find the highest rated movie of each genre
# looping on groups
for group, data in genre:
    print(group)
    print(data)

Action
                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
Adventure
                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
Animation
                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
Biography
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
Comedy
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
Crime
                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
Drama
                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
Family
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
Fantasy
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
Film-Noir
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
Horror
                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
Mystery
          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
Thriller
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore

In [11]:
# apply -> builtin function
genre.apply(min)

C:\Users\Qazi\AppData\Local\Temp\ipykernel_11648\1242808603.py:2: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genre.apply(min)
C:\Users\Qazi\AppData\Local\Temp\ipykernel_11648\1242808603.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [12]:
movies.sample()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
147,The Wolf of Wall Street,2013,180,Biography,8.2,Martin Scorsese,Leonardo DiCaprio,1187498,116900694.0,75.0

In [13]:
# find number of movies starting with A for each group
def start_with_A(group):
    return group['Series_Title'].str.startswith('A').sum()

In [14]:
movies.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='object')

In [15]:
# find ranking of each movie in the group according to IMDB score
def ranking(group):
    group['Ranking'] = group['IMDB_Rating'].rank(ascending=False)
    return group

In [16]:
genre.apply(ranking)

C:\Users\Qazi\AppData\Local\Temp\ipykernel_11648\3984914510.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(ranking)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  Ranking
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0      1.0
         5          Elijah Wood      1642758  377845905.0       94.0      2.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0      3.5
         10         Elijah Wood      1661481  315544750.0       92.0      3.5
         13         Elijah Wood      1485555  342551365.0       87.0      6.0
...                         ...          ...          ...        ...      ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0      1.0
Western  12      Clint Eastwood       688390    6100000.0       90.0      1.0
         48         Henry Fonda       302844    5321508.0       80.0      2.0
         115     Clint Eastwood       232772   15000000.0       74.0      3.0
         691     Clint Eastwood        65659   31800000.0       69.0      4.0

[1000 rows x 11 columns]